name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
           docker build . --file Dockerfile -t myd/mydkoan
           docker save "myd/mydkoan" -o "12.tar"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: 12.tar
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
    
