# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
on:
 workflow_dispatch:
  inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
  - name:ad
   runs: |
     docker build . --file Dockerfile
   
   
