# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
on:
 workflow_dispatch:
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name:ad
   runs:
    using: 'docker'
    image: 'Dockerfile'
    args: - ${{ inputs.who-to-greet }}
