name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
           docker build . --file Dockerfile -t myd/mydkoan
           docker save "myd/mydkoan" -o "12.tar"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: 12.tar
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
    
