# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
on:
 workflow_dispatch:
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
  - name:ad
   runs: |
     docker build . --file Dockerfile
   
   
